#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated by SimpleNeural-DSL Compiler
Source: examples/minimal.sndsl
"""

# ==================== IMPORTS ====================
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings("ignore")

# Set random seeds for reproducibility
tf.random.set_seed(42)
np.random.seed(42)


# ==================== DATA LOADING ====================
def load_and_preprocess_data():
    """Load dataset and perform preprocessing."""
    print("[INFO] Loading dataset: simple_data.csv")

    try:
        df = pd.read_csv("simple_data.csv")
    except FileNotFoundError:
        raise FileNotFoundError(
            f"Dataset 'simple_data.csv' not found. "
            "Please ensure the file is in the current directory."
        )

    # Separate features and target
    if "y" not in df.columns:
        raise ValueError(
            f"Target column 'y' not found. "
            f"Available columns: {list(df.columns)}"
        )

    y = df.pop("y")
    X = df

    # Handle missing values
    if X.isnull().any().any():
        print("[WARNING] Dataset contains missing values. Filling with mean...")
        X = X.fillna(X.mean())

    # Feature scaling
    print("[INFO] Applying StandardScaler to features...")
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y,
        test_size=0.2,
        random_state=42
    )

    print(f"[INFO] Training samples: {len(X_train)}")
    print(f"[INFO] Test samples: {len(X_test)}")
    print(f"[INFO] Number of features: {X_train.shape[1]}")

    return X_train, X_test, y_train, y_test, scaler


# ==================== MODEL DEFINITION ====================
def build_model(input_shape):
    """Build the neural network model: SimpleModel"""
    print("[INFO] Building model: SimpleModel")

    model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(input_shape=(input_shape,)),
        tf.keras.layers.Dense(32, activation="relu", name="dense_0"),
        tf.keras.layers.Dense(1, activation="linear", name="dense_1"),
    ], name="SimpleModel")

    # Configure optimizer
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

    # Compile model
    model.compile(
        optimizer=optimizer,
        loss="mse",
        metrics=["mae", "mse"]
    )

    return model


# ==================== TRAINING ====================
def train_model(model, X_train, y_train, X_test, y_test):
    """Train the model with specified parameters."""
    print("\n[INFO] Starting training...")
    print("=" * 50)

    # Callbacks
    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=10,
            restore_best_weights=True,
            verbose=1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=5,
            min_lr=1e-6,
            verbose=1
        )
    ]

    # Training
    history = model.fit(
        X_train, y_train,
        epochs=50,
        batch_size=32,
        validation_split=0.2,
        callbacks=callbacks,
        verbose=1
    )

    return history


# ==================== EVALUATION ====================
def evaluate_model(model, X_test, y_test):
    """Evaluate model performance on test set."""
    print("\n[INFO] Evaluating model on test set...")
    print("=" * 50)

    results = model.evaluate(X_test, y_test, verbose=0)

    print(f"Test Loss (MSE): {results[0]:.4f}")
    print(f"Test MAE: {results[1]:.4f}")
    print(f"Test RMSE: {np.sqrt(results[0]):.4f}")

    # Predictions
    predictions = model.predict(X_test, verbose=0)

    # R² Score
    r2 = r2_score(y_test, predictions)
    print(f"R² Score: {r2:.4f}")

    return results, predictions


# ==================== MAIN ====================
def main():
    """Main execution function."""
    print("=" * 60)
    print("SimpleNeural-DSL Generated Model")
    print("=" * 60)

    # Load data
    X_train, X_test, y_train, y_test, scaler = load_and_preprocess_data()

    # Build model
    model = build_model(input_shape=X_train.shape[1])

    # Show model summary
    print("\n[INFO] Model Architecture:")
    model.summary()

    # Train model
    history = train_model(model, X_train, y_train, X_test, y_test)

    # Evaluate model
    results, predictions = evaluate_model(model, X_test, y_test)

    # Save model
    model_path = "trained_model.keras"
    model.save(model_path)
    print(f"\n[INFO] Model saved to: {model_path}")

    print("\n" + "=" * 60)
    print("Training completed successfully!")
    print("=" * 60)

    return model, history, scaler


if __name__ == "__main__":
    model, history, scaler = main()